Annotations for the StorageUnitType
Tsireledzo2/Storage-Rental-System-2.0 pull request #72
Opened 2023-08-06 14:37 UTC by Ruvimbo21Ndoro

2023-08-06 21:02 UTC, Tsireledzo2 requested changes
the code need changes not right the storsgeunit clas not here and pom file not updated and storage unit type class calling it self which is wrong

2023-08-06 21:03 UTC, Tsireledzo2 commented on pom.xml
The pom file must be updated to the latest onhe

2023-08-06 21:04 UTC, Ruvimbo21Ndoro commented
Didn't you say l must only do the storageunitType

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Tsireledzo Makhado ***@***.***>
Sent: Sunday, August 6, 2023 11:02:47 PM
To: Tsireledzo2/Storage-Rental-System-2.0 ***@***.***>
Cc: Ruvimbo Ndoro ***@***.***>; Author ***@***.***>
Subject: Re: [Tsireledzo2/Storage-Rental-System-2.0] Annotations for the StorageUnitType (PR #72)


@Tsireledzo2 requested changes on this pull request.

the code need changes not right the storsgeunit clas not here and pom file not updated and storage unit type class calling it self which is wrong

—
Reply to this email directly, view it on GitHub<https://github.com/Tsireledzo2/Storage-Rental-System-2.0/pull/72#pullrequestreview-1564201844>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYMVYACEG5BOAWCRFJYSRCLXUAA7PANCNFSM6AAAAAA3F6VFPM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-06 21:04 UTC, Tsireledzo2 commented on src/main/java/za/ac/cput/domain/StorageUnitType.java
> +    private StorageUnitType storageUnitType;
This is wrong must not be here

2023-08-06 21:04 UTC, Tsireledzo2 commented on src/main/java/za/ac/cput/domain/StorageUnitType.java
> +    public StorageUnitType getStorageUnitType() {
same as this not suppose to be here

2023-08-06 21:04 UTC, Tsireledzo2 commented on src/main/java/za/ac/cput/domain/StorageUnitType.java
> +    public void setStorageUnitType(StorageUnitType storageUnitType) {
even this

2023-08-06 21:04 UTC, Ruvimbo21Ndoro commented
I followed what you told me to do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ruvimbo Ndoro ***@***.***>
Sent: Sunday, August 6, 2023 11:04:00 PM
To: Tsireledzo2/Storage-Rental-System-2.0 ***@***.***>; Tsireledzo2/Storage-Rental-System-2.0 ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [Tsireledzo2/Storage-Rental-System-2.0] Annotations for the StorageUnitType (PR #72)

Didn't you say l must only do the storageunitType

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Tsireledzo Makhado ***@***.***>
Sent: Sunday, August 6, 2023 11:02:47 PM
To: Tsireledzo2/Storage-Rental-System-2.0 ***@***.***>
Cc: Ruvimbo Ndoro ***@***.***>; Author ***@***.***>
Subject: Re: [Tsireledzo2/Storage-Rental-System-2.0] Annotations for the StorageUnitType (PR #72)


@Tsireledzo2 requested changes on this pull request.

the code need changes not right the storsgeunit clas not here and pom file not updated and storage unit type class calling it self which is wrong

—
Reply to this email directly, view it on GitHub<https://github.com/Tsireledzo2/Storage-Rental-System-2.0/pull/72#pullrequestreview-1564201844>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYMVYACEG5BOAWCRFJYSRCLXUAA7PANCNFSM6AAAAAA3F6VFPM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-06 21:06 UTC, Tsireledzo2 commented
use the code here [`here click here please`](https://github.com/Tsireledzo2/Storage-Rental-System/tree/updateStorageUnit)

2023-08-23 13:34 UTC, Tsireledzo2 commented
When will you update the code?

2023-08-23 13:35 UTC, Tsireledzo2 commented on pom.xml
don't remove anything on the pomfile

2023-08-25 22:43 UTC, Tsireledzo2 commented on src/main/java/za/ac/cput/repository/StorageUnitRepository.java
>      public Set<StorageUnit> getAll();
Change Set to List

2023-08-28 07:12 UTC, Tsireledzo2 approved these changes

2023-08-28 07:12 UTC, merged